### ISSUE TITLE
Consider ensuring "unzip" is installed

### ISSUE THREAD

**Issue by anned20** [nleiva/ansible-role-grafana_agent#2]
Installing this on a server without `unzip` leads to this error:

```fatal: [1.1.1.1]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/tmp/agent-linux.zip\". Make sure the required command to extract the file is installed. Command \"/usr/bin/tar\" could not handle archive. Unable to find required 'unzip' or 'zipinfo' binary in the path."}```

Maybe add a task to ensure that the `unzip` command is available?

**Comment by nleiva** [comment]
Fixed with https://github.com/nleiva/ansible-role-grafana_agent/commit/8ca68bad2dce00f14f3a0e0ee3fde77b3786984f

**Comment by anned20** [comment]
Thank you!
