### ISSUE TITLE
Support other regions

### ISSUE THREAD

**Issue by anned20** [nleiva/ansible-role-grafana_agent#3]
The endpoint is currently hardcoded, but I had to change it to use it in Europe.

**Comment by nleiva** [comment]
Thank you, I didn't know they had multi-region/zone support. I added this as a variable you can provide an input in https://github.com/nleiva/ansible-role-grafana_agent/commit/db84596dd8974b7522bd0732cc3901e43a2f7706

**Comment by spech66** [comment]
One remark: for EU the full URL is `prometheus-prod-01-eu-west-0`
If you define `grafana_location: eu-west-0` this will result in `prometheus-eu-west-0.grafana.net`

**Comment by nleiva** [comment]
Thanks @spech66. Could you open an issue to track this separately.
