### ISSUE TITLE
Custom URL for other regions

### ISSUE THREAD

**Issue by spech66** [nleiva/ansible-role-grafana_agent#8]
In some regions some of the services (prometheus, graphite, rules engine, ...) have a different URL schema 

* https://logs-prod-eu-west-0.grafana.net
* https://prometheus-prod-01-eu-west-0.grafana.net/api/prom

In `agent-config.yaml.j2` the definition is `url: https://prometheus-{{ grafana_location }}.grafana.net/api/prom/push`
and `promtail-config.yaml.j2` contains `https://{{ loki_user }}:{{ grafana_api_key }}@logs-prod-{{ grafana_location }}.grafana.net/api/prom/push`
You can't change `grafana_location=prod-01-eu-west-0` as this would break promtail.

I would suggest one of this solutions:
1) Have a var for every service e.g. `grafana_location_prometheus=prometheus-prod-01-eu-west-0.grafana.net` (more flexible)
2) Have a service specific prefix `grafana_location_prometheus=prometheus-prod-01` (more compatible to existing config)

**Comment by spech66** [comment]
Currently I use the `grafana_agent_config_template` config override as workaround to define prod-01.

**Comment by nleiva** [comment]
@spech66 check out the PR @josuablejeru just merged and see if it solves this issue. Thanks.

**Comment by spech66** [comment]
Thank you! Already tested it and it seems to work!
